# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release on Docker

on: 
  workflow_dispatch:
    inputs:
      cerberusVersion:
        description: 'Version'     
        required: true
        default: '1'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build docker
      run: |
        echo "$(ls)"
        cd docker/images/cerberus-as-tomcat/${{ github.event.inputs.cerberusVersion }}
        echo "$(ls)"
        docker build -t bcivel/cerberus-as-tomcat:${{ github.event.inputs.cerberusVersion }} .
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: bcivel/cerberus-as-tomcat:${{ github.event.inputs.cerberusVersion }}
        
#docker tag 272a813d0a8e cerberustesting/cerberus-as-glassfish:latest)
#Push the latest to docker hub (docker push cerberustesting/cerberus-as-glassfish:latest)

