# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: 
  workflow_dispatch:
    inputs:
      amenCookieValue:
        description: 'Amen Cookie Value'     
        required: true
        default: ''
      domain:
        description: 'Cerberus Domain'     
        required: true
        default: 'app06'


jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: https://controlpanel.amen.fr/async/dns/zoneHnd.html -X POST -H "Content-Type:application/x-www-form-urlencoded" -H "Accept-Language:fr-fr" -H "Accept-Encoding:gzip, deflate, br" -H "User-Agent:Mozilla/5.0 \(Macintosh; Intel Mac OS X 10_15_6\) AppleWebKit/605.1.15 \(KHTML, like Gecko\) Version/14.0.2 Safari/605.1.15"  -H "Host:controlpanel.amen.fr" -H "Origin:https://controlpanel.amen.fr" -H "Connection:keep-alive" -H "Referer:https://controlpanel.amen.fr/domains/dns.html" -H "Content-Length:82" -H "Cookie:_ashkii=JSON_eyJzaWQiOiI3MzYxOTZlM2Y2NDkzMjYwODliZmM2M2Q2NTUwZGQ3YiIsImNrdGltZSI6IjE2MjQ0NDEwNTEiLCJzc3AiOiI0OSIsInBwIjoiQTAwIn0%3D; _fbp=fb.1.1622212138339.2032282488; _wicasa=JSON_eyJjaWQiOiI0ZjQwNmI0Mjk1NTNiMTQ1YTM1MjAyZjJmNGZmMGM4OSIsImNrdGltZSI6IjE2MjQ0NDEwNTEiLCJzY3AiOiI0OSIsInBrIjoiTTA1IiwiY2tib3JuIjoiMTYxMTM5OTIzNSIsImxhc3RyZWYiOiJjb250cm9scGFuZWwuYW1lbi5mclwvZG9tYWluc1wvZG5zLmh0bWwiLCJsYXN0ZG9tc3JjIjoiIiwiaXNjbGkiOiIxIn0%3D; cc_cookie_accept={%22marketing%22:true%2C%22necessary%22:true%2C%22preferences%22:true%2C%22statistics%22:true}; cookid=4f406b429553b145a35202f2f4ff0c89; dbmFP=736196e3f649326089bfc63d6550dd7b.A00; dbmPK=736196e3f649326089bfc63d6550dd7b.M05; _ga=GA1.2.198958871.1622212138; _gid=GA1.2.708728643.1624312620; gb_cp_s=eJyLVkpOLUpKLSot1i1JLS7JzEvXS87P1cEQzC9K11GKBQCbXBFE; cto_bundle=LPazC19QN1VGM3ZWMTJ5cDl2cW1RaHFWd2w4ZmpDaE40NUxLM1RhbFFDJTJCcVJPZUN2WEN6N0hvRUIzZnFOU21jVWgzVUxlV1RyT3V3N3B2VWdBaGVIVTNiU3dIc0I2bDdzZk9ybm9MM0t1VnJBRUxRVzZVcTRzcmt6ZlljendYS1hKeWNTc2NwZ21XYUFJaEUlMkZhNkk4SXRUVnJwSmFYTjZOVGJhNlRTZDNsSnpGazVJJTNF; USERID=BD4181-AMFR; USERLOGGED=B%26nbsp%3BDUMONT; cpIsLogged=1LevelLogged; dpsid=${{ github.event.inputs.amenCookieValue }}; gb_cp_b=0; JSESSIONID=6495257895152792240.SID01; CookieConsent={stamp:%276bn3kjMdaptTLffRV51DeNbPKTC66ZwVy6AJ7s817pDwlb26huyDHA==%27%2Cnecessary:true%2Cpreferences:true%2Cstatistics:true%2Cmarketing:true%2Cver:1%2Cutc:1623839815937%2Cregion:%27fr%27}" -H "X-Requested-With:XMLHttpRequest" --data "action=addCNAME&confirmed=true&CNAME=toto&selectedCNAME=${{ github.event.inputs.domain }}.cerberus-testing.com"
        
